# Generated by Django 4.1.2 on 2022-10-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_rename_song_id_lyric_song_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='artiste_id',
        ),
    ]
