# Generated by Django 4.1.2 on 2022-10-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_rename_song_lyric_song_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiste',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AlterModelOptions(
            name='lyric',
            options={'ordering': ('song_id',)},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('title',)},
        ),
    ]
